# R8 rules for the release build.
#
# The release build previously ran with isMinifyEnabled = false, so this file
# was referenced but never existed and nothing was ever shrunk or obfuscated.
# Everything below keeps a class that is looked up reflectively at runtime and
# would otherwise be renamed or stripped, leaving a crash that only appears in
# release builds.

# ── Moshi ────────────────────────────────────────────────────────────────────
# Adapters are generated by KSP and found by name at runtime.
-keep class com.ezhil.app.data.remote.dto.**JsonAdapter { *; }
-keepnames class com.ezhil.app.data.remote.dto.** { *; }
-keepclassmembers class com.ezhil.app.data.remote.dto.** {
    <init>(...);
    <fields>;
}
-keep class com.squareup.moshi.** { *; }
-keep interface com.squareup.moshi.** { *; }
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
-keepclassmembers @com.squareup.moshi.JsonClass class * { <init>(...); }

# ── Retrofit / OkHttp ────────────────────────────────────────────────────────
# Retrofit builds implementations from the interface's generic signatures and
# annotations, both of which R8 would otherwise discard.
-keepattributes Signature, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepattributes AnnotationDefault
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-if interface * { @retrofit2.http.* public *** *(...); }
-keep,allowoptimization,allowshrinking,allowobfuscation class <3>
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn retrofit2.**

# OkHttp references these only on the JVM; they are absent on Android.
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

# ── Room ─────────────────────────────────────────────────────────────────────
-keep class * extends androidx.room.RoomDatabase { <init>(); }
-keep @androidx.room.Entity class * { *; }
-dontwarn androidx.room.paging.**

# ── Hilt / Dagger ────────────────────────────────────────────────────────────
-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }
-keep class * extends dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper { *; }
-keepclasseswithmembers class * { @javax.inject.Inject <init>(...); }

# ── On-device ML ─────────────────────────────────────────────────────────────
# TFLite and ONNX Runtime cross into native code by name; renaming breaks the
# screening model and the Tamil OCR fallback.
-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.gpu.** { *; }
-dontwarn org.tensorflow.lite.gpu.**
-keep class ai.onnxruntime.** { *; }
-dontwarn ai.onnxruntime.**
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**

# ── Kotlin ───────────────────────────────────────────────────────────────────
-keepclassmembers class kotlin.Metadata { public <methods>; }
-dontwarn kotlin.**
-keepclassmembers class **$WhenMappings { <fields>; }
-keepclassmembers class kotlinx.serialization.json.** { *; }

# ── WorkManager ──────────────────────────────────────────────────────────────
# Workers are instantiated by name from a persisted job record.
-keep class * extends androidx.work.Worker
-keep class * extends androidx.work.CoroutineWorker
-keep class com.ezhil.app.sync.** { *; }

# ── Diagnostics ──────────────────────────────────────────────────────────────
# Keep line numbers so a crash report from a school is readable, but hide the
# original source file name.
-keepattributes SourceFile, LineNumberTable
-renamesourcefileattribute SourceFile
